//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSubType
    {
        public int AccountSubTypeID { get; set; }
        public int AccountTypeID { get; set; }
        public string AccountSubTypeCode { get; set; }
        public string SubTypeName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AccountType AccountType { get; set; }
    }
}
