//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddProduct
    {
        public int ProductId { get; set; }
        public string Brand { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
        public string ProdcutCode { get; set; }
        public string ProdcutName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
