//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string RegistationNumber { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string PoBox { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Telephone01 { get; set; }
        public string Telephone02 { get; set; }
        public string Fax { get; set; }
        public string VatRegistationNo { get; set; }
        public string NBTNo { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual Group Group { get; set; }
    }
}
