//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string RegistationNumber { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Telephone01 { get; set; }
        public string Telephone02 { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifideBy { get; set; }
        public bool IsActive { get; set; }
        public int BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
