//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastSixMonthsanalisiReorder
    {
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Location_ToId { get; set; }
        public string Last5Month { get; set; }
        public Nullable<decimal> Last5MonthQTY { get; set; }
        public string Last4Month { get; set; }
        public Nullable<decimal> Last4MonthQTY { get; set; }
        public string Last3Month { get; set; }
        public Nullable<decimal> Last3MonthQTY { get; set; }
        public string Last2Month { get; set; }
        public Nullable<decimal> Last2MonthQTY { get; set; }
        public string LastMonth { get; set; }
        public Nullable<decimal> LastMonthQTY { get; set; }
        public string ThisMonth { get; set; }
        public Nullable<decimal> ThisMonthQTY { get; set; }
        public decimal TodayUsageQTY { get; set; }
        public Nullable<decimal> last6MonthsAvg { get; set; }
        public Nullable<decimal> lastYearAvg { get; set; }
    }
}
