//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int TaxID { get; set; }
        public string TaxCode { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.DateTime> BeginningOfthevalidTime { get; set; }
        public Nullable<System.DateTime> EndOfthevalidTime { get; set; }
        public string Description { get; set; }
        public string ApplicableOn { get; set; }
        public string FillingFreqency { get; set; }
        public string ReportingMethod { get; set; }
        public Nullable<bool> TaxCollectedOnSales { get; set; }
        public Nullable<bool> TaxCollectedOnPurchase { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
