//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_StockAdj
    {
        public int ProductId { get; set; }
        public string Product_ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> StockAdjustmentId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Location_ToId { get; set; }
        public string Description { get; set; }
        public string RefNo { get; set; }
        public Nullable<decimal> Expr2 { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> ReceivedQtyPrice { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public Nullable<decimal> IssuedQtyPrice { get; set; }
    }
}
