//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW01.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LOCATIONWISERPT
    {
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> Location_FromId { get; set; }
        public Nullable<int> Location_ToId { get; set; }
        public string SiteRegistrationName { get; set; }
        public Nullable<int> MaterialReturnId { get; set; }
        public Nullable<int> StockTranferId { get; set; }
        public Nullable<int> GRNId { get; set; }
        public Nullable<int> ReturnId { get; set; }
        public Nullable<int> GoodTransferId { get; set; }
        public Nullable<int> StockAdjustmentId { get; set; }
        public string Discription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TempTotal { get; set; }
    }
}
